source 'https://github.com/CocoaPods/Specs.git'

platform:ios, '9.0'

install! 'cocoapods',
:deterministic_uuids => false

inhibit_all_warnings!

target 'JKCycleScroll' do
    pod 'SDWebImage'
    
end
